/*
 Copyright (c) 2026, Hippocrates Technologies Sagl. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification,
 are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation and/or
 other materials provided with the distribution.

 3. Neither the name of the copyright holder(s) nor the names of any contributor(s) may
 be used to endorse or promote products derived from this software without specific
 prior written permission. No license is granted to the trademarks of the copyright
 holders even if such marks are included in this software.

 4. Commercial redistribution in any form requires an explicit license agreement with the
 copyright holder(s). Please contact support@hippocratestech.com for further information
 regarding licensing.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 OF SUCH DAMAGE.
 */

import Foundation
import Combine
import HealthKit
import OTFCareKit
import OTFCareKitStore
import OTFCloudClientAPI
import PDFKit
import Testing
@testable import OTFMagicBox

@Suite("ECG report generation")
struct ECGReportTests {
    private let date = Date(timeIntervalSinceReferenceDate: 789012)

    @Test("Synthetic waveform is deterministic and complete")
    func syntheticWaveformIsDeterministicAndComplete() throws {
        let first = ECGWaveform.synthetic(
            averageBPM: 72,
            duration: 30,
            samplingFrequencyHz: 512
        )
        let second = ECGWaveform.synthetic(
            averageBPM: 72,
            duration: 30,
            samplingFrequencyHz: 512
        )

        #expect(first == second)
        #expect(first.samples.count == 15360)
        #expect(first.samplingFrequencyHz == 512)
        #expect(first.duration > 29.99)
        #expect(first.samples.allSatisfy {
            $0.timeSinceSampleStart.isFinite && $0.millivolts.isFinite
        })
    }

    @Test("Renderer creates one landscape PDF with provenance")
    func rendererCreatesLandscapePDFWithProvenance() throws {
        let report = try #require(makeReport())
        let document = try #require(PDFDocument(data: report.pdfData))
        let page = try #require(document.page(at: 0))
        let text = try #require(document.string)

        #expect(report.pdfData.starts(with: Data("%PDF-".utf8)))
        #expect(report.pdfData.count < 1000000)
        #expect(document.pageCount == 1)
        #expect(page.bounds(for: .mediaBox).width > page.bounds(for: .mediaBox).height)
        #expect(text.contains("Electrocardiogram"))
        #expect(text.contains("Sinus Rhythm"))
        #expect(text.contains("Generated by MagicBox"))
        #expect(text.contains("not Apple Health's exported PDF"))
    }

    @Test("Sensor ECG report has exact ordered outcome contract")
    func sensorReportHasExactOutcomeContract() throws {
        let report = try #require(makeReport())
        let attachment = try #require(makeAttachment(for: report))
        let payload = SensorOutcomePayload(
            metric: .ecg,
            reading: makeReading(),
            mode: .sensor,
            notes: "  Recorded after resting  ",
            ecgReportAttachment: attachment
        )

        let values = SensorOutcomeCodec.encode(payload)

        #expect(values.map(\.kind) == [
            "classification",
            "averageBPM",
            "samplingHz",
            "duration",
            "healthKitSampleUUID",
            "lead",
            "ecgReportFormat",
            "ecgReportMimeType",
            "ecgReportAttachmentID",
            "ecgReportFileName",
            "ecgReportEncryptedFileKey",
            "ecgReportHashFileKey",
            "date",
            "entryMode",
            "notes"
        ])
        #expect(values.map(\.type) == [
            .integer,
            .double,
            .double,
            .double,
            .text,
            .text,
            .text,
            .text,
            .text,
            .text,
            .text,
            .text,
            .date,
            .text,
            .text
        ])
        #expect(values[4].stringValue == attachment.sourceSampleUUID?.uuidString)
        #expect(values[5].stringValue == ECGWaveform.appleWatchLead)
        #expect(values[6].stringValue == ECGReport.formatVersion)
        #expect(values[7].stringValue == ECGReport.mimeType)
        #expect(values[8].stringValue == attachment.attachmentID)
        #expect(values[9].stringValue == attachment.fileName)
        #expect(values[10].stringValue == attachment.encryptedFileKey)
        #expect(values[11].stringValue == attachment.hashFileKey)
        #expect(values[13].stringValue == SensorTaskMode.sensor.rawValue)
        #expect(values[14].stringValue == "Recorded after resting")
        #expect(!values.contains { $0.type == .binary })
        #expect(SensorOutcomeCodec.decode(metric: .ecg, values: values) == .payload(payload))
    }

    @Test("CareKit and JSON preserve the secure attachment reference")
    func careKitAndJSONPreserveAttachmentReference() throws {
        let report = try #require(makeReport())
        let attachment = try #require(makeAttachment(for: report))
        let payload = SensorOutcomePayload(
            metric: .ecg,
            reading: makeReading(),
            mode: .sensor,
            ecgReportAttachment: attachment
        )
        let outcome = OCKOutcome(
            taskUUID: UUID(),
            taskOccurrenceIndex: 2,
            values: SensorOutcomeCodec.encode(payload)
        )

        let data = try JSONEncoder().encode(outcome)
        let decodedOutcome = try JSONDecoder().decode(OCKOutcome.self, from: data)
        let decoded = SensorOutcomeCodec.decode(metric: .ecg, values: decodedOutcome.values)

        #expect(decodedOutcome.values == outcome.values)
        #expect(decoded == .payload(payload))
        guard case .payload(let decodedPayload) = decoded else {
            Issue.record("Expected a named ECG payload")
            return
        }
        #expect(decodedPayload.ecgReport == nil)
        #expect(decodedPayload.ecgReportAttachment == attachment)
        #expect(!decodedOutcome.values.contains { $0.type == .binary })
    }

    @Test("Reports are omitted from manual and non-ECG outcomes")
    func reportsAreRestrictedToSensorECG() throws {
        let report = try #require(makeReport())
        let manual = SensorOutcomePayload(
            metric: .ecg,
            reading: makeReading(),
            mode: .manual,
            ecgReport: report
        )
        let heartRate = SensorOutcomePayload(
            metric: .heartRate,
            reading: .heartRate(bpm: 72, date: date),
            mode: .sensor,
            ecgReport: report
        )

        #expect(manual.ecgReport == nil)
        #expect(heartRate.ecgReport == nil)
        #expect(!SensorOutcomeCodec.encode(manual).contains { $0.type == .binary })
        #expect(!SensorOutcomeCodec.encode(heartRate).contains { $0.type == .binary })
    }

    @Test("Incomplete report metadata does not invalidate scalar ECG data")
    func incompleteReportMetadataDoesNotInvalidateScalarData() throws {
        let report = try #require(makeReport())
        let attachment = try #require(makeAttachment(for: report))
        let payload = SensorOutcomePayload(
            metric: .ecg,
            reading: makeReading(),
            mode: .sensor,
            ecgReportAttachment: attachment
        )
        let values = SensorOutcomeCodec.encode(payload).filter {
            $0.kind != SensorOutcomeValueKind.ecgReportMimeType.rawValue
        }

        let expected = SensorOutcomePayload(
            metric: .ecg,
            reading: makeReading(),
            mode: .sensor
        )
        #expect(SensorOutcomeCodec.decode(metric: .ecg, values: values) == .payload(expected))
    }

    @Test("Attachment store uploads ciphertext and decrypts downloaded reports")
    func attachmentStoreRoundTripsEncryptedReport() async throws {
        let report = try #require(makeReport())
        let attachmentID = "ecg-attachment-1"
        let storageKey = Array(repeating: UInt8(0x24), count: 32)
        var storedData = Data()
        var storedEncryptedKey = ""
        var storedHash = ""
        var storedFileName = ""
        var uploadedLocation: Request.AttachmentLocation?
        let isolatedDefaults = makeIsolatedUserDefaults(prefix: "ecg-attachment-store")
        defer { isolatedDefaults.cleanup() }
        let registry = ECGReportAttachmentRegistry(
            defaults: isolatedDefaults.defaults,
            namespace: { "test-user" }
        )

        let store = ECGReportAttachmentStore(
            storageKey: { storageKey },
            uploadRequest: { data, fileName, location, encryptedKey, hash in
                storedData = data
                storedEncryptedKey = encryptedKey
                storedHash = hash
                storedFileName = fileName
                uploadedLocation = location
                return Just(Response.FileResponse(
                    metadata: makeMetadata(
                        attachmentID: attachmentID,
                        fileName: fileName,
                        encryptedFileKey: encryptedKey,
                        hashFileKey: hash
                    ),
                    data: data
                ))
                .setFailureType(to: ForgeError.self)
                .eraseToAnyPublisher()
            },
            downloadRequest: { requestedID, location in
                #expect(requestedID == attachmentID)
                #expect(location == .documents)
                return Just(Response.FileResponse(
                    metadata: makeMetadata(
                        attachmentID: attachmentID,
                        fileName: storedFileName,
                        encryptedFileKey: storedEncryptedKey,
                        hashFileKey: storedHash
                    ),
                    data: storedData
                ))
                .setFailureType(to: ForgeError.self)
                .eraseToAnyPublisher()
            },
            deleteRequest: { _ in
                Just(Response.DeleteFile(error: false, message: "Deleted", statusCode: 200))
                    .setFailureType(to: ForgeError.self)
                    .eraseToAnyPublisher()
            },
            registry: registry
        )

        let attachment = try await upload(report, using: store).get()
        let downloaded = try await download(attachment, using: store).get()

        #expect(uploadedLocation == .documents)
        #expect(storedData != report.pdfData)
        #expect(attachment.attachmentID == attachmentID)
        #expect(downloaded == report)
        #expect(registry.pendingAttachmentIDs == [attachmentID])
    }

    @Test("Attachment download rejects substituted response metadata")
    func attachmentDownloadRejectsSubstitutedMetadata() async throws {
        let report = try #require(makeReport())
        let storageKey = Array(repeating: UInt8(0x24), count: 32)
        let envelope = try SecureAttachmentCryptor().encrypt(
            report.pdfData,
            storageKey: storageKey
        )
        let attachment = try #require(makeAttachment(
            for: report,
            encryptedFileKey: envelope.encryptedFileKey,
            hashFileKey: envelope.hashFileKey
        ))
        let cases = [
            makeMetadata(
                attachmentID: "different-attachment",
                fileName: attachment.fileName,
                encryptedFileKey: envelope.encryptedFileKey,
                hashFileKey: envelope.hashFileKey
            ),
            makeMetadata(
                attachmentID: attachment.attachmentID,
                fileName: "different.pdf",
                encryptedFileKey: envelope.encryptedFileKey,
                hashFileKey: envelope.hashFileKey
            ),
            makeMetadata(
                attachmentID: attachment.attachmentID,
                fileName: attachment.fileName,
                encryptedFileKey: envelope.encryptedFileKey,
                hashFileKey: envelope.hashFileKey,
                location: .profile
            ),
            makeMetadata(
                attachmentID: attachment.attachmentID,
                fileName: attachment.fileName,
                encryptedFileKey: envelope.encryptedFileKey + "00",
                hashFileKey: envelope.hashFileKey
            ),
            makeMetadata(
                attachmentID: attachment.attachmentID,
                fileName: attachment.fileName,
                encryptedFileKey: envelope.encryptedFileKey,
                hashFileKey: envelope.hashFileKey + "00"
            )
        ]

        for metadata in cases {
            let store = makeAttachmentStore(
                storageKey: storageKey,
                downloadResponse: Response.FileResponse(
                    metadata: metadata,
                    data: envelope.encryptedData
                )
            )

            switch await download(attachment, using: store) {
            case .success:
                Issue.record("Substituted attachment metadata was accepted")
            case .failure(let error):
                #expect(
                    error as? ECGReportAttachmentStoreError == .invalidAttachmentMetadata
                )
            }
        }
    }

    @Test("Attachment upload rejects altered encryption metadata")
    func attachmentUploadRejectsAlteredEncryptionMetadata() async throws {
        let report = try #require(makeReport())
        let store = ECGReportAttachmentStore(
            storageKey: { Array(repeating: UInt8(0x24), count: 32) },
            uploadRequest: { data, fileName, _, encryptedKey, hash in
                Just(Response.FileResponse(
                    metadata: makeMetadata(
                        attachmentID: "ecg-attachment",
                        fileName: fileName,
                        encryptedFileKey: encryptedKey + "00",
                        hashFileKey: hash
                    ),
                    data: data
                ))
                .setFailureType(to: ForgeError.self)
                .eraseToAnyPublisher()
            }
        )

        switch await upload(report, using: store) {
        case .success:
            Issue.record("Altered upload metadata was accepted")
        case .failure(let error):
            #expect(error as? ECGReportAttachmentStoreError == .invalidAttachmentMetadata)
        }
    }

    @Test("Secure attachment is persisted by occurrence without binary outcome data")
    func secureAttachmentIsPersistedByOccurrence() async throws {
        let report = try #require(makeReport())
        let attachment = try #require(makeAttachment(for: report))
        let attachmentStore = FakeECGReportAttachmentStore(uploadResult: .success(attachment))
        let task = makeTask(id: "secure-ecg-outcome", start: date, end: nil)
        let event = try #require(SensorTaskOutcomeHelper.event(for: task, on: date))
        let careKitStore = OCKStore(
            name: "SecureECGOutcomeTests-\(UUID().uuidString)",
            type: .inMemory
        )
        try await add(task: task, to: careKitStore)

        let success = await send(
            SensorOutcomePayload(
                metric: .ecg,
                reading: makeReading(),
                mode: .sensor,
                ecgReport: report
            ),
            task: task,
            occurrence: event.occurrence,
            store: careKitStore,
            attachmentStore: attachmentStore
        )
        let outcomes = try await fetchOutcomes(from: careKitStore, on: date)
        let outcome = try #require(outcomes.first)

        #expect(success)
        #expect(attachmentStore.uploadedReports == [report])
        #expect(attachmentStore.committedAttachments.count == 1)
        #expect(attachmentStore.committedAttachments.first?.attachmentID == attachment.attachmentID)
        #expect(attachmentStore.committedAttachments.first?.ownerID == task.uuid.uuidString)
        #expect(outcome.taskOccurrenceIndex == event.occurrence)
        #expect(!outcome.values.contains { $0.type == .binary })
        guard case .payload(let persistedPayload) = SensorOutcomeCodec.decode(
            metric: .ecg,
            values: outcome.values
        ) else {
            Issue.record("Expected a named ECG outcome")
            return
        }
        #expect(persistedPayload.ecgReport == nil)
        #expect(persistedPayload.ecgReportAttachment == attachment)
    }

    @Test("Failed CareKit persistence deletes a newly uploaded ECG attachment")
    func failedPersistenceDeletesNewAttachment() async throws {
        let report = try #require(makeReport())
        let attachment = try #require(makeAttachment(for: report))
        let attachmentStore = FakeECGReportAttachmentStore(uploadResult: .success(attachment))
        let task = makeTask(id: "missing-secure-ecg-task", start: date, end: nil)
        let event = try #require(SensorTaskOutcomeHelper.event(for: task, on: date))
        let careKitStore = OCKStore(
            name: "SecureECGOutcomeFailureTests-\(UUID().uuidString)",
            type: .inMemory
        )

        let success = await send(
            SensorOutcomePayload(
                metric: .ecg,
                reading: makeReading(),
                mode: .sensor,
                ecgReport: report
            ),
            task: task,
            occurrence: event.occurrence,
            store: careKitStore,
            attachmentStore: attachmentStore
        )

        #expect(!success)
        #expect(attachmentStore.deletedAttachmentIDs == [attachment.attachmentID])
        #expect(try await fetchOutcomes(from: careKitStore, on: date).isEmpty)
    }

    @Test("Attachment upload failure prevents outcome persistence")
    func uploadFailurePreventsPersistence() async throws {
        let report = try #require(makeReport())
        let attachmentStore = FakeECGReportAttachmentStore(
            uploadResult: .failure(ECGReportTestError.failed)
        )
        let task = makeTask(id: "failed-secure-ecg-upload", start: date, end: nil)
        let event = try #require(SensorTaskOutcomeHelper.event(for: task, on: date))
        let careKitStore = OCKStore(
            name: "SecureECGUploadFailureTests-\(UUID().uuidString)",
            type: .inMemory
        )
        try await add(task: task, to: careKitStore)

        let success = await send(
            SensorOutcomePayload(
                metric: .ecg,
                reading: makeReading(),
                mode: .sensor,
                ecgReport: report
            ),
            task: task,
            occurrence: event.occurrence,
            store: careKitStore,
            attachmentStore: attachmentStore
        )

        #expect(!success)
        #expect(attachmentStore.deletedAttachmentIDs.isEmpty)
        #expect(try await fetchOutcomes(from: careKitStore, on: date).isEmpty)
    }

    @MainActor
    @Test("Submitted outcome downloads its secure ECG report and retries failures")
    func submittedOutcomeDownloadsAndRetriesReport() throws {
        let report = try #require(makeReport())
        let attachment = try #require(makeAttachment(for: report))
        let attachmentStore = FakeECGReportAttachmentStore(
            uploadResult: .success(attachment)
        )
        attachmentStore.downloadResult = .failure(ECGReportTestError.failed)
        let task = makeTask(id: "download-secure-ecg", start: date, end: nil)
        let event = try #require(SensorTaskOutcomeHelper.event(for: task, on: date))
        let payload = SensorOutcomePayload(
            metric: .ecg,
            reading: makeReading(),
            mode: .sensor,
            ecgReportAttachment: attachment
        )
        let outcome = OCKOutcome(
            taskUUID: task.uuid,
            taskOccurrenceIndex: event.occurrence,
            values: SensorOutcomeCodec.encode(payload)
        )
        let careKitStore = OCKStore(
            name: "SecureECGDownloadTests-\(UUID().uuidString)",
            type: .inMemory
        )
        let model = SensorTaskDetailViewModel(
            task: task,
            selectedDate: date,
            occurrence: event.occurrence,
            storeManager: OCKSynchronizedStoreManager(wrapping: careKitStore),
            metric: .ecg,
            mode: .sensor,
            outcomeFetcher: { _, _, completion in
                completion(.success([outcome]))
            },
            attachmentStore: attachmentStore
        )

        model.refresh()
        #expect(model.ecgReportState == .failed)
        attachmentStore.downloadResult = .success(report)
        model.retryECGReportDownload()

        #expect(model.ecgReportState == .loaded(report))
        #expect(attachmentStore.downloadedAttachments == [attachment, attachment])
    }

    @MainActor
    @Test("A stale ECG download cannot overwrite a newer retry")
    func staleECGDownloadCannotOverwriteNewerRetry() throws {
        let report = try #require(makeReport())
        let attachment = try #require(makeAttachment(for: report))
        let attachmentStore = ControlledECGReportAttachmentStore()
        let task = makeTask(id: "ordered-ecg-download", start: date, end: nil)
        let event = try #require(SensorTaskOutcomeHelper.event(for: task, on: date))
        let outcome = OCKOutcome(
            taskUUID: task.uuid,
            taskOccurrenceIndex: event.occurrence,
            values: SensorOutcomeCodec.encode(SensorOutcomePayload(
                metric: .ecg,
                reading: makeReading(),
                mode: .sensor,
                ecgReportAttachment: attachment
            ))
        )
        let careKitStore = OCKStore(
            name: "OrderedECGDownloadTests-\(UUID().uuidString)",
            type: .inMemory
        )
        let model = SensorTaskDetailViewModel(
            task: task,
            selectedDate: date,
            occurrence: event.occurrence,
            storeManager: OCKSynchronizedStoreManager(wrapping: careKitStore),
            metric: .ecg,
            mode: .sensor,
            outcomeFetcher: { _, _, completion in completion(.success([outcome])) },
            attachmentStore: attachmentStore
        )

        model.refresh()
        model.retryECGReportDownload()
        #expect(attachmentStore.pendingDownloadCount == 2)

        attachmentStore.completeDownload(at: 1, with: .success(report))
        attachmentStore.completeDownload(at: 0, with: .failure(ECGReportTestError.failed))

        #expect(model.ecgReportState == .loaded(report))
    }

    private func makeReading() -> HealthKitDataManager.HealthMetricValue {
        .ecg(
            classification: .sinusRhythm,
            averageBPM: 82,
            samplingHz: 512,
            duration: 30,
            date: date
        )
    }

    private func makeReport() -> ECGReport? {
        let waveform = ECGWaveform(
            sourceSampleUUID: UUID(uuidString: "669A7A1E-F4DE-42CC-8AA0-7F548980919A"),
            lead: ECGWaveform.appleWatchLead,
            samplingFrequencyHz: 512,
            samples: ECGWaveform.synthetic(averageBPM: 82).samples
        )
        return ECGReportRenderer().makeReport(reading: makeReading(), waveform: waveform)
    }

    private func makeAttachment(
        for report: ECGReport,
        encryptedFileKey: String = "encrypted-file-key",
        hashFileKey: String = "file-key-hash"
    ) -> ECGReportAttachment? {
        ECGReportAttachment(
            attachmentID: "ecg-attachment-1",
            fileName: "MagicBox-ECG-Test.pdf",
            encryptedFileKey: encryptedFileKey,
            hashFileKey: hashFileKey,
            sourceSampleUUID: report.sourceSampleUUID,
            lead: report.lead,
            format: report.format,
            mimeType: report.mimeType
        )
    }

    private func send(
        _ payload: SensorOutcomePayload,
        task: OCKAnyTask,
        occurrence: Int,
        store: OCKStore,
        attachmentStore: ECGReportAttachmentStoring
    ) async -> Bool {
        await withCheckedContinuation { continuation in
            SensorTaskOutcomeHelper.sendOutcome(
                payload: payload,
                task: task,
                on: date,
                occurrence: occurrence,
                storeManager: OCKSynchronizedStoreManager(wrapping: store),
                attachmentStore: attachmentStore,
                environment: .current(now: date)
            ) { success in
                continuation.resume(returning: success)
            }
        }
    }
}

@Suite("ECG outcome session isolation")
struct ECGOutcomeSessionIsolationTests {
    private let date = Date(timeIntervalSinceReferenceDate: 789012)

    @MainActor
    @Test("Account switch during upload rejects outcome persistence and sync")
    func accountSwitchDuringUploadRejectsPersistenceAndSync() async throws {
        let report = try #require(ECGReport(
            pdfData: Data("%PDF-1.7 account switch".utf8),
            sourceSampleUUID: nil
        ))
        let attachment = try #require(ECGReportAttachment(
            attachmentID: "account-bound-attachment",
            fileName: "MagicBox-ECG-Test.pdf",
            encryptedFileKey: "encrypted-file-key",
            hashFileKey: "file-key-hash",
            sourceSampleUUID: nil
        ))
        let attachmentStore = ControlledUploadECGReportAttachmentStore()
        let task = makeTask(id: "account-bound-secure-ecg", start: date, end: nil)
        let event = try #require(SensorTaskOutcomeHelper.event(for: task, on: date))
        let initiatingStore = OCKStore(
            name: "AccountBoundSecureECGTests-\(UUID().uuidString)",
            type: .inMemory
        )
        try await add(task: task, to: initiatingStore)
        var activeSession = "patient-a"
        var syncCount = 0

        let success = await withCheckedContinuation { continuation in
            SensorTaskOutcomeHelper.sendOutcome(
                payload: SensorOutcomePayload(
                    metric: .ecg,
                    reading: .ecg(
                        classification: .sinusRhythm,
                        averageBPM: 82,
                        samplingHz: 512,
                        duration: 30,
                        date: date
                    ),
                    mode: .sensor,
                    ecgReport: report
                ),
                task: task,
                on: date,
                occurrence: event.occurrence,
                storeManager: OCKSynchronizedStoreManager(wrapping: initiatingStore),
                attachmentStore: attachmentStore,
                environment: SensorOutcomeSubmissionEnvironment(
                    now: date,
                    sessionIdentity: { activeSession },
                    scheduleSync: { _ in
                        syncCount += 1
                        return true
                    }
                ),
                completion: { continuation.resume(returning: $0) }
            )

            activeSession = "patient-b"
            attachmentStore.completeUpload(with: .success(attachment))
        }

        #expect(success == false)
        #expect(syncCount == 0)
        #expect(attachmentStore.deletedAttachmentIDs == [attachment.attachmentID])
        #expect(attachmentStore.committedAttachments.isEmpty)
        #expect(try await fetchOutcomes(from: initiatingStore, on: date).isEmpty)
    }
}

@Suite("ECG attachment metadata compatibility")
struct ECGReportAttachmentMetadataTests {
    @Test("Attachment round trip accepts omitted backend filenames")
    func attachmentRoundTripAcceptsOmittedBackendFileNames() async throws {
        let report = try #require(ECGReport(
            pdfData: Data("%PDF-1.7 filename compatibility".utf8),
            sourceSampleUUID: nil
        ))
        let attachmentID = "ecg-without-backend-filename"
        let storageKey = Array(repeating: UInt8(0x24), count: 32)
        var encryptedData = Data()
        var encryptedFileKey = ""
        var hashFileKey = ""
        let store = ECGReportAttachmentStore(
            storageKey: { storageKey },
            uploadRequest: { data, _, _, encryptedKey, hash in
                encryptedData = data
                encryptedFileKey = encryptedKey
                hashFileKey = hash
                return Just(Response.FileResponse(
                    metadata: makeMetadata(
                        attachmentID: attachmentID,
                        fileName: "",
                        encryptedFileKey: encryptedKey,
                        hashFileKey: hash
                    ),
                    data: data
                ))
                .setFailureType(to: ForgeError.self)
                .eraseToAnyPublisher()
            },
            downloadRequest: { _, _ in
                Just(Response.FileResponse(
                    metadata: makeMetadata(
                        attachmentID: attachmentID,
                        fileName: "",
                        encryptedFileKey: encryptedFileKey,
                        hashFileKey: hashFileKey
                    ),
                    data: encryptedData
                ))
                .setFailureType(to: ForgeError.self)
                .eraseToAnyPublisher()
            }
        )

        let attachment = try await upload(report, using: store).get()
        let downloadedReport = try await download(attachment, using: store).get()

        #expect(attachment.fileName.isEmpty == false)
        #expect(downloadedReport == report)
    }
}

private enum ECGReportTestError: Error {
    case failed
}

private final class FakeECGReportAttachmentStore: ECGReportAttachmentStoring {
    let uploadResult: Result<ECGReportAttachment, Error>
    var downloadResult: Result<ECGReport, Error> = .failure(ECGReportTestError.failed)
    private(set) var uploadedReports = [ECGReport]()
    private(set) var downloadedAttachments = [ECGReportAttachment]()
    private(set) var deletedAttachmentIDs = [String]()
    private(set) var committedAttachments = [(attachmentID: String, ownerID: String)]()
    private(set) var reconciledAttachmentIDs = [Set<String>]()

    init(uploadResult: Result<ECGReportAttachment, Error>) {
        self.uploadResult = uploadResult
    }

    func upload(
        report: ECGReport,
        completion: @escaping (Result<ECGReportAttachment, Error>) -> Void
    ) {
        uploadedReports.append(report)
        completion(uploadResult)
    }

    func download(
        attachment: ECGReportAttachment,
        completion: @escaping (Result<ECGReport, Error>) -> Void
    ) {
        downloadedAttachments.append(attachment)
        completion(downloadResult)
    }

    func delete(
        attachmentID: String,
        completion: @escaping (Result<Void, Error>) -> Void
    ) {
        deletedAttachmentIDs.append(attachmentID)
        completion(.success(()))
    }

    func markCommitted(attachmentID: String, ownerID: String) {
        committedAttachments.append((attachmentID, ownerID))
    }

    func reconcile(referencedAttachmentIDs: Set<String>) {
        reconciledAttachmentIDs.append(referencedAttachmentIDs)
    }
}

private final class ControlledECGReportAttachmentStore: ECGReportAttachmentStoring {
    private var downloads = [((Result<ECGReport, Error>) -> Void)?]()

    var pendingDownloadCount: Int {
        downloads.compactMap { $0 }.count
    }

    func upload(
        report: ECGReport,
        completion: @escaping (Result<ECGReportAttachment, Error>) -> Void
    ) {
        completion(.failure(ECGReportTestError.failed))
    }

    func download(
        attachment: ECGReportAttachment,
        completion: @escaping (Result<ECGReport, Error>) -> Void
    ) {
        downloads.append(completion)
    }

    func delete(
        attachmentID: String,
        completion: @escaping (Result<Void, Error>) -> Void
    ) {
        completion(.success(()))
    }

    func completeDownload(
        at index: Int,
        with result: Result<ECGReport, Error>
    ) {
        let completion = downloads[index]
        downloads[index] = nil
        completion?(result)
    }
}

private final class ControlledUploadECGReportAttachmentStore: ECGReportAttachmentStoring {
    private var uploadCompletion: ((Result<ECGReportAttachment, Error>) -> Void)?
    private(set) var deletedAttachmentIDs = [String]()
    private(set) var committedAttachments = [(attachmentID: String, ownerID: String)]()

    func upload(
        report: ECGReport,
        completion: @escaping (Result<ECGReportAttachment, Error>) -> Void
    ) {
        uploadCompletion = completion
    }

    func download(
        attachment: ECGReportAttachment,
        completion: @escaping (Result<ECGReport, Error>) -> Void
    ) {
        completion(.failure(ECGReportTestError.failed))
    }

    func delete(
        attachmentID: String,
        completion: @escaping (Result<Void, Error>) -> Void
    ) {
        deletedAttachmentIDs.append(attachmentID)
        completion(.success(()))
    }

    func markCommitted(attachmentID: String, ownerID: String) {
        committedAttachments.append((attachmentID, ownerID))
    }

    func completeUpload(with result: Result<ECGReportAttachment, Error>) {
        let completion = uploadCompletion
        uploadCompletion = nil
        completion?(result)
    }
}

private func makeValue(
    _ value: OCKOutcomeValueUnderlyingType,
    kind: SensorOutcomeValueKind
) -> OCKOutcomeValue {
    var outcomeValue = OCKOutcomeValue(value)
    outcomeValue.kind = kind.rawValue
    return outcomeValue
}

private func makeMetadata(
    attachmentID: String,
    fileName: String,
    encryptedFileKey: String,
    hashFileKey: String,
    location: Request.AttachmentLocation = .documents
) -> Response.Metadata {
    Response.Metadata(
        contentType: "application/octet-stream",
        revpos: "1",
        hashFileKey: hashFileKey,
        encryptedFileKey: encryptedFileKey,
        location: location.rawValue,
        fileName: fileName,
        owner: "test-user",
        attrev: 1,
        length: 1,
        stub: false,
        attachmentID: attachmentID
    )
}

private func makeAttachmentStore(
    storageKey: [UInt8],
    downloadResponse: Response.FileResponse
) -> ECGReportAttachmentStore {
    ECGReportAttachmentStore(
        storageKey: { storageKey },
        downloadRequest: { _, _ in
            Just(downloadResponse)
                .setFailureType(to: ForgeError.self)
                .eraseToAnyPublisher()
        }
    )
}

private func makeECGForgeError(message: String) -> ForgeError {
    ForgeError(error: .init(
        statusCode: 500,
        name: "ECGReportTests",
        message: message,
        code: nil
    ))
}

private func upload(
    _ report: ECGReport,
    using store: ECGReportAttachmentStoring
) async -> Result<ECGReportAttachment, Error> {
    await withCheckedContinuation { continuation in
        store.upload(report: report) { continuation.resume(returning: $0) }
    }
}

private func download(
    _ attachment: ECGReportAttachment,
    using store: ECGReportAttachmentStoring
) async -> Result<ECGReport, Error> {
    await withCheckedContinuation { continuation in
        store.download(attachment: attachment) { continuation.resume(returning: $0) }
    }
}

private func add(task: OCKTask, to store: OCKStore) async throws {
    let result = await withCheckedContinuation { continuation in
        store.addAnyTask(task, callbackQueue: .main) { continuation.resume(returning: $0) }
    }
    if case .failure(let error) = result {
        throw error
    }
}

private func fetchOutcomes(from store: OCKStore, on date: Date) async throws -> [OCKAnyOutcome] {
    let result = await withCheckedContinuation { continuation in
        store.fetchAnyOutcomes(
            query: OCKOutcomeQuery(for: date),
            callbackQueue: .main
        ) { continuation.resume(returning: $0) }
    }
    switch result {
    case .success(let outcomes):
        return outcomes
    case .failure(let error):
        throw error
    }
}
