/*
 Copyright (c) 2026, Hippocrates Technologies Sagl. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification,
 are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation and/or
 other materials provided with the distribution.

 3. Neither the name of the copyright holder(s) nor the names of any contributor(s) may
 be used to endorse or promote products derived from this software without specific
 prior written permission. No license is granted to the trademarks of the copyright
 holders even if such marks are included in this software.

 4. Commercial redistribution in any form requires an explicit license agreement with the
 copyright holder(s). Please contact support@hippocratestech.com for further information
 regarding licensing.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 OF SUCH DAMAGE.
 */

import Foundation

enum ECGReportCopy {
    static let title = String(
        localized: "ECG Report",
        comment: "Title for a generated electrocardiogram report"
    )
    static let generatedReport = String(
        localized: "Generated Report",
        comment: "Title for an ECG report generated by MagicBox"
    )
    static let openFullReport = String(
        localized: "Open Full Report",
        comment: "Action that opens the complete ECG report"
    )
    static let shareReport = String(
        localized: "Share Report",
        comment: "Action that shares the generated ECG report"
    )
    static let done = String(localized: "Done", comment: "Dismisses the ECG report")
    static let previewAccessibilityLabel = String(
        localized: "MagicBox generated electrocardiogram report preview",
        comment: "Accessibility label for the ECG PDF preview"
    )
    static let openAccessibilityHint = String(
        localized: "Opens the complete generated ECG report",
        comment: "Accessibility hint for opening the ECG report"
    )
    static let provenance = String(
        localized: "Generated by MagicBox from HealthKit ECG voltage data. This is not Apple Health's exported PDF.",
        comment: "Explains the provenance of a generated ECG report"
    )
    static let averageUnavailable = String(
        localized: "Average heart rate unavailable",
        comment: "Shown when an ECG has no average heart rate"
    )

    static func averageBPM(_ bpm: Int) -> String {
        String(
            localized: "\(bpm) BPM Average",
            comment: "Average heart rate in an ECG report"
        )
    }

    static func calibration(samplingFrequencyHz: Int) -> String {
        String(
            localized: "25 mm/s - 10 mm/mV - Lead I - \(samplingFrequencyHz) Hz",
            comment: "ECG report calibration and sampling details"
        )
    }
}
