name: Testing
on:
  push:
    branches:
    - development
jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.11.3
      - name: Github Credentials Store Setup
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.REPO_USERNAME }}:${{ secrets.ACCESS_TOKEN }}@github.com" > ~/.git-credentials
      - name: Install pods
        run: pod install
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
